### ISSUE TITLE
Enable HTTPS Support for OAuth2 Logins

### ISSUE THREAD

**Issue by zb13y** [mypaint/mypaint.github.io#27] opened 2016-04-18 08:04 UTC
Sorry, there was an error authorizing your account. Perhaps you did not approve authorization?

**Comment by odysseywestra** [comment] 2016-04-18 14:32
@achadwick could you update the urls for Twitter and Github to HTTPS please? I was able to fix for the Google Login.

**Comment by odysseywestra** [comment] 2016-04-18 14:47
The Problem was the we forgot to update the urls on out OAuth2 Logins to https since we added SSL encryption to our site through Let's Encrypt. It's fixed for the Google Login since for now it under my account, but @achadwick needs to fix the other two since he has control of those two ends.

**Comment by achadwick** [comment] 2016-04-18 16:05
Twitter logins should be fixed now. Please test.

**Comment by achadwick** [comment] 2016-04-18 16:09
Github logins too. I've just tested this myself :smile: 

`s/http:/https:/` for the homepage and callback URIs for both services. Seems to work fine with existing tokens, and doesn't require them to be regenerated.

**Comment by odysseywestra** [comment] 2016-04-18 16:33
Okay I can confirm it work with Github login, but can with twitter since my account isn't connected to it. Can someone confirm for it us?

**Comment by odysseywestra** [comment] 2016-04-18 16:37
@achadwick I did turn on the force HTTPS option on Discourse. So technically we don't need have the http part added to the URL's.

**Comment by achadwick** [comment] 2016-04-18 16:44
Twitter tested too with a newly created account. All done here, I think.

Thanks for getting HTTPS set up, @odysseywestra !

**Closed by achadwick** 2016-04-18 16:44 UTC
Labels: Bug, Discourse Site
