### ISSUE TITLE
Error prevents submit private message

### ISSUE THREAD

**Issue by alexandre-mbm** [mypaint/mypaint.github.io#23] opened 2016-01-21 03:06 UTC
![mypaint-cantsentpm](https://cloud.githubusercontent.com/assets/957501/12470412/ac93ff28-bfd2-11e5-9ca3-fb57fc369d36.png)

**Comment by odysseywestra** [comment] 2016-01-21 03:11
Are you trying to send it with a blank subject?

On Wed, Jan 20, 2016, 7:06 PM Alexandre Magno <notifications@github.com>
wrote:

> [image: mypaint-cantsentpm]
> <https://cloud.githubusercontent.com/assets/957501/12470412/ac93ff28-bfd2-11e5-9ca3-fb57fc369d36.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mypaint/mypaint.github.io/issues/23>.
>
-- 

-- Albert Westra

**Comment by odysseywestra** [comment] 2016-01-21 03:11
Please give me steps to reproduce this please.

On Wed, Jan 20, 2016, 7:11 PM Albert Westra <odysseywestra@gmail.com> wrote:

> Are you trying to send it with a blank subject?
>
> On Wed, Jan 20, 2016, 7:06 PM Alexandre Magno <notifications@github.com>
> wrote:
>
>> [image: mypaint-cantsentpm]
>> <https://cloud.githubusercontent.com/assets/957501/12470412/ac93ff28-bfd2-11e5-9ca3-fb57fc369d36.png>
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/mypaint/mypaint.github.io/issues/23>.
>>
> --
>
> -- Albert Westra
>
-- 

-- Albert Westra

**Comment by alexandre-mbm** [comment] 2016-01-21 03:23
**Note:** respond to issues through email dirty the page at GitHub.

> Are you trying to send it with a blank subject?

![mypaint-cantsentpm](https://cloud.githubusercontent.com/assets/957501/12470710/36d80916-bfd5-11e5-8949-05dbe21dff87.png)

> Please give me steps to reproduce this please.

See red marks in image above please.

**Comment by odysseywestra** [comment] 2016-01-21 22:12
Okay, once again, discourse is doing as it designed to do. You are still at Trust Level 0 (New User): Here's what you can and can't do at Trust Level 0:

>New (0)

>Discourse does not quite trust new users yet, as they are visitors who just created an account, still learning the community norms and the way your forum works. Whether accidentally, or intentionally, new users can cause problems in your community.

>We also want to hide any so-called "advanced" functionality from new users to make the UI less confusing for them and gently land them on the deeper UI as they get more experienced.

>Thus, new users' abilities are restricted for safety -- both theirs and yours.

>Users at trust level 0 cannot...

>   Send private messages to other users
>    Reply as new topic in the right gutter (UI removed)
>    Flag posts
>    Post more than 1 image
>    Post any attachments
>    Post more than 2 hyperlinks in a post
>    Have actual links in the 'about me' field of their profile (will be silently and temporarily converted to plain text)
>    Mention more than 2 users in a post


This is taken from this thread on http://meta.discourse.org: 
https://meta.discourse.org/t/what-do-user-trust-levels-do/4924/2

I've also add this link to our [FAQ](http://community.mypaint.org/faq) to explain how the Trust System works.

However with that said, I do believe Discourse should let you know it's because of your Trust Level and not "Topic Cannot Be Blank". I'll be sure to bring this up on the Discourse Forums.

I'm closing this issue since Discourses is working as Designed. No further action is needed.

**Closed by odysseywestra** 2016-01-21 22:12 UTC

**Comment by alexandre-mbm** [comment] 2016-01-21 23:03
> > Users at trust level 0 cannot...
> > Send private messages to other users
>
> I'll be sure to bring this up on the Discourse Forums.

Thank you.
